#!/bin/sh

# Make sure required plugins are installed and up to date
while read -r line; do
  bundle=$(echo $line| cut -d '/' -f 2)
  printf "Updating $bundle... "
  if [ -d "bundle/$bundle" ]; then
    pushd bundle/$bundle &> /dev/null
    git pull
    popd &> /dev/null
  else
    git clone https://github.com/$line bundle/$bundle
  fi
done < vimrc.bundles

# Kill any plugins no longer required
for dir in bundle/*; do
  bundle=$(echo $dir| cut -d '/' -f 2)
  if ! grep -q $bundle vimrc.bundles vimrc.bundles-no-install; then
    echo Killing $bundle
    rm -rf $dir
  fi
done
